pipeline {
    agent {label 'STAGE-1'}
    environment {
        PROJECT = 'expense'
        COMPONENT = 'backend'
        appVersion = ''
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }
    stages {
        stage ('INIT') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                            terraform plan
                        """
                    }
                }
            }
        }

        stage('APPLY') {
            input {
                message "should we continue ?"
                ok "yes, please go ahead"
            }
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                        sh """
                            cd 10-sg/
                            terraform apply -auto-approve

                        """
                    }
                }
            }
        }
    }
    post {
        always {
            echo " This is a joindevops Expense project build"
            deleteDir()
        }
        failure {
            echo " This pipeline is failed for some reason"
        }
        success {
            echo "This pipeline is success"
        }
    }
}